name: main

on:
  push:
    tags: ['*']

jobs:
  build:
    name: Build wheels on ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Set up Python
        uses: actions/setup-python@v5
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16
        env:
          CIBW_BUILD: cp38-*
          CIBW_ARCHS_LINUX: native
          CIBW_ARCHS_WINDOWS: native
          CIBW_ARCHS_MACOS: x86_64 arm64
      - name: Upload wheelhouse artifact
        uses: actions/upload-artifact@v4
        with:
          name: wheelhouse
          path: wheelhouse/*.whl
          retention-days: 1

  upload:
    name: Upload wheels to PyPI
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download wheelhouse artifact
        uses: actions/download-artifact@v4
        with:
          name: wheelhouse
          path: dist
      - uses: pypa/gh-action-pypi-publish@v1.8.12
        with:
          password: ${{secrets.PYPI_TOKEN}}
